// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ClientFileExists() {
  return window['go']['main']['App']['ClientFileExists']();
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DownloadClientFile() {
  return window['go']['main']['App']['DownloadClientFile']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function InsertProxy(arg1) {
  return window['go']['main']['App']['InsertProxy'](arg1);
}

export function OpenGithub() {
  return window['go']['main']['App']['OpenGithub']();
}

export function RunProxy(arg1) {
  return window['go']['main']['App']['RunProxy'](arg1);
}

export function StopProxy(arg1) {
  return window['go']['main']['App']['StopProxy'](arg1);
}

export function UpdateProxy(arg1) {
  return window['go']['main']['App']['UpdateProxy'](arg1);
}
