// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function ClientFileExists():Promise<boolean>;

export function DeleteProxy(arg1:number):Promise<Error>;

export function DownloadClientFile():Promise<void>;

export function GetLogs(arg1:number):Promise<Array<main.Log>>;

export function GetProxies():Promise<Array<main.Proxy>>;

export function InsertProxy(arg1:main.Proxy):Promise<Error>;

export function OpenGithub():Promise<void>;

export function RunProxy(arg1:number):Promise<Error>;

export function StopProxy(arg1:number):Promise<Error>;

export function UpdateProxy(arg1:main.Proxy):Promise<Error>;
